-- AlterTable
ALTER TABLE "ApTitle" ADD COLUMN "paymentDate" TIMESTAMP(3);
ALTER TABLE "ApTitle" ADD COLUMN "paidAmount" DOUBLE PRECISION;
ALTER TABLE "ApTitle" ADD COLUMN "discountReceived" DOUBLE PRECISION;
ALTER TABLE "ApTitle" ADD COLUMN "interestReceived" DOUBLE PRECISION;
